/* eslint-disable @typescript-eslint/no-unused-vars */
"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { signOut } from "next-auth/react";
import { Activity, BadgePercent, BarChart3, Bell, ChevronDown, ChevronRight, CircleHelp, Command, CreditCard, FileText, Home, LogOut, Mail, Menu, Megaphone, Package, PanelLeftClose, PanelLeftOpen, Plus, Search, Settings, ShoppingBag, Store, Tags, UserRound, Users, X, Zap } from "lucide-react";

const navigation = [
  { label:"Home", href:"/admin/dashboard", icon:Home },
  { label:"Orders", href:"/admin/orders", icon:ShoppingBag },
  { label:"Products", href:"/admin/products", icon:Package, children:[["All products","/admin/products"],["Inventory","/admin/products/inventory"],["Categories","/admin/products/categories"],["Collections","/admin/products/collections"],["Brands","/admin/products/brands"]] },
  { label:"Customers", href:"/admin/customers", icon:Users },
  { label:"Messages", href:"/admin/contact-messages", icon:Mail, children:[["Contact messages","/admin/contact-messages"],["Newsletter","/admin/newsletter"]] },
  { label:"Marketing", href:"/admin/marketing", icon:Megaphone },
  { label:"Discounts", href:"/admin/discounts", icon:BadgePercent },
  { label:"Content", href:"/admin/content/pages", icon:FileText, children:[["Pages","/admin/content/pages"],["Blogs","/admin/content/blogs"],["Navigation","/admin/content/navigation"],["Media","/admin/content/media"]] },
  { label:"Analytics", href:"/admin/analytics", icon:BarChart3 },
  { label:"Online Store", href:"/", icon:Store },
  { label:"Configuration", href:"/admin/settings/payments", icon:CreditCard, children:[["Payments","/admin/settings/payments"],["Shipping","/admin/settings/shipping"],["Taxes","/admin/settings/taxes"]] },
  { label:"Settings", href:"/admin/settings/general", icon:Settings },
];
export function AdminShell({ children, admin }:{ children:React.ReactNode; admin:{name:string;email:string} }){
  const pathname=usePathname(); const router=useRouter();
  const [collapsed,setCollapsed]=useState(false); const [mobile,setMobile]=useState(false); const [palette,setPalette]=useState(false); const [profile,setProfile]=useState(false); const [quick,setQuick]=useState(false); const [notifications,setNotifications]=useState(false);
  const [expanded,setExpanded]=useState<string[]>(["Products"]);
  useEffect(()=>{setCollapsed(localStorage.getItem("electzo-admin-sidebar")==="collapsed")},[]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setPalette(true)}if(e.key==="Escape"){setPalette(false);setQuick(false);setProfile(false)}};addEventListener("keydown",key);return()=>removeEventListener("keydown",key)},[]);
  function toggleCollapse(){setCollapsed(v=>{localStorage.setItem("electzo-admin-sidebar",!v?"collapsed":"expanded");return !v})}
  const crumbs=pathname.split("/").filter(Boolean).slice(1);
  return <div className={`adm-app ${collapsed?"is-collapsed":""}`}>
    {mobile&&<button className="adm-drawer-shade" onClick={()=>setMobile(false)} aria-label="Close menu"/>}
    <aside className={`adm-sidebar ${mobile?"is-mobile-open":""}`}><div className="adm-side-brand"><span><Zap size={18} fill="currentColor"/></span><b>Electzo<small>ADMIN</small></b><button className="adm-mobile-close" onClick={()=>setMobile(false)}><X/></button></div><nav className="adm-nav">{navigation.map(item=>{const active=pathname===item.href||pathname.startsWith(item.href+"/");const open=expanded.includes(item.label);const Icon=item.icon;return <div key={item.label} className="adm-nav-group"><div className={`adm-nav-row ${active?"active":""}`}><Link href={item.href} onClick={()=>setMobile(false)} title={collapsed?item.label:undefined}><Icon/><span>{item.label}</span></Link>{item.children&&<button onClick={()=>setExpanded(s=>open?s.filter(x=>x!==item.label):[...s,item.label])}><ChevronRight className={open?"rotated":""}/></button>}</div>{item.children&&open&&!collapsed&&<div className="adm-subnav">{item.children.map(([label,href])=><Link key={href} className={pathname===href?"active":""} href={href} onClick={()=>setMobile(false)}>{label}</Link>)}</div>}</div>})}</nav><div className="adm-side-bottom"><Link href="/admin/profile"><span className="adm-avatar">{admin.name[0]?.toUpperCase()}</span><span><b>{admin.name}</b><small>Administrator</small></span></Link><button onClick={()=>signOut({callbackUrl:"/admin/login"})} title="Logout"><LogOut/></button></div><button className="adm-collapse" onClick={toggleCollapse}>{collapsed?<PanelLeftOpen/>:<PanelLeftClose/>}<span>Collapse sidebar</span></button></aside>
    <section className="adm-workspace"><header className="adm-header"><button className="adm-menu" onClick={()=>setMobile(true)}><Menu/></button><div className="adm-breadcrumb"><Link href="/admin/dashboard">Admin</Link>{crumbs.map((c,i)=><span key={c}><ChevronRight/> <b>{c.replaceAll("-"," ")}</b></span>)}</div><button className="adm-global-search" onClick={()=>setPalette(true)}><Search/><span>Search products, orders, customers...</span><kbd><Command/>K</kbd></button><div className="adm-head-actions"><div className="adm-pop"><button className="adm-quick" onClick={()=>setQuick(!quick)}><Plus/> <span>Create</span><ChevronDown/></button>{quick&&<div className="adm-menu-pop">{[["Product","/admin/products/new",Package],["Order","/admin/orders",ShoppingBag],["Customer","/admin/customers",UserRound],["Discount","/admin/discounts",Tags]].map(([l,h,I])=><Link key={h as string} href={h as string} onClick={()=>setQuick(false)}>{(()=>{const Icon=I as typeof Package;return <Icon/>})()}{l as string}</Link>)}</div>}</div><div className="adm-pop"><button className="adm-icon-btn" onClick={()=>setNotifications(!notifications)}><Bell/><i/></button>{notifications&&<div className="adm-notify-pop"><header><b>Notifications</b><button>Mark all read</button></header><p><span>!</span><b>Inventory alert<small>4 products are running low on stock.</small></b></p><p><span>₹</span><b>New orders<small>Review your latest customer orders.</small></b></p><Link href="/admin/notifications">View all notifications</Link></div>}</div><button className="adm-icon-btn"><CircleHelp/></button><div className="adm-pop"><button className="adm-head-profile" onClick={()=>setProfile(!profile)}><span>{admin.name[0]?.toUpperCase()}</span><div><b>{admin.name}</b><small>Administrator</small></div><ChevronDown/></button>{profile&&<div className="adm-profile-pop"><div><b>{admin.name}</b><small>{admin.email}</small></div><Link href="/admin/profile">Profile</Link><Link href="/admin/settings/general">Account settings</Link><button onClick={()=>signOut({callbackUrl:"/admin/login"})}><LogOut/> Log out</button></div>}</div></div></header><main className="adm-content">{children}</main></section>
    {palette&&<div className="adm-palette-shade" onMouseDown={e=>{if(e.target===e.currentTarget)setPalette(false)}}><div className="adm-palette"><header><Search/><input autoFocus placeholder="Search or jump to..."/><kbd>ESC</kbd></header><section><small>QUICK ACTIONS</small>{[["Create product","/admin/products/new",Plus],["Open orders","/admin/orders",ShoppingBag],["View analytics","/admin/analytics",Activity],["Open settings","/admin/settings/general",Settings]].map(([l,h,I])=><button key={h as string} onClick={()=>{router.push(h as string);setPalette(false)}}>{(()=>{const Icon=I as typeof Plus;return <Icon/>})()}<span>{l as string}</span><ChevronRight/></button>)}</section></div></div>}
  </div>
}
